"""replaced rate with descriptioon

Revision ID: b78aea1d085b
Revises: 733d91ccfd4c
Create Date: 2025-04-15 19:13:03.826280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78aea1d085b'
down_revision: Union[str, None] = '733d91ccfd4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('sessions', 'productivity_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('productivity_rate', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'description')
    # ### end Alembic commands ###
