"""added activity status 

Revision ID: faacac24cbcf
Revises: b78aea1d085b
Create Date: 2025-04-22 17:20:10.084801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faacac24cbcf'
down_revision: Union[str, None] = 'b78aea1d085b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute('UPDATE sessions SET is_active = FALSE')
    op.alter_column('sessions', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'is_active')
    # ### end Alembic commands ###
